import type { ScenarioPreset } from './types'

export const scenarioPresets: Record<string, ScenarioPreset> = {
  planning: {
    label: 'Planning Sprint',
    delegation: 'Main → Logic',
    workers: [
      {
        id: 'main',
        name: 'Main',
        role: 'Manager / Orchestrator',
        model: 'openai-codex/gpt-5.4',
        status: 'working',
        task: 'Designing MVP flow and delegating UI implementation',
        lastCompleted: 'Created Agent Office scaffold',
        location: 'Command Desk',
        energy: 'Focused',
        queue: 2,
        duration: '07m',
        lastActiveLabel: 'just now',
        persona: {
          icon: '👩‍💼',
          tone: 'Calm orchestrator',
          specialty: 'Planning and delegation',
        },
      },
      {
        id: 'vision',
        name: 'Vision',
        role: 'OCR / Image Analyst',
        model: 'google/gemini-2.5-flash',
        status: 'sleeping',
        task: 'Waiting for screenshots, assets, or document review',
        lastCompleted: 'Prepared OCR-focused specialist profile',
        location: 'Document Station',
        energy: 'Sleeping',
        queue: 0,
        duration: 'Idle',
        lastActiveLabel: '8m ago',
        persona: {
          icon: '🧾',
          tone: 'Precise reader',
          specialty: 'Text extraction and image understanding',
        },
      },
      {
        id: 'logic',
        name: 'Logic',
        role: 'Code Drafter',
        model: 'anthropic/claude-sonnet-4-6',
        status: 'idle',
        task: 'Standing by for component and state-model subtasks',
        lastCompleted: 'Returned successful spawn test output',
        location: 'Dev Desk',
        energy: 'Ready',
        queue: 1,
        duration: 'Standby',
        lastActiveLabel: '2m ago',
        persona: {
          icon: '👩‍💻',
          tone: 'Systematic builder',
          specialty: 'Readable code and maintainable logic',
        },
      },
    ],
    monitoring: {
      source: 'mock',
      lastUpdatedLabel: 'local preset',
    },
    timeline: [
      {
        id: 1,
        actorId: 'main',
        kind: 'handoff',
        title: 'Main is leading MVP planning',
        detail: 'Preparing architecture and mapping next coding tasks for Logic.',
        time: 'Now',
        targetId: 'logic',
        tags: ['planning', 'ui'],
      },
      {
        id: 2,
        actorId: 'logic',
        kind: 'task_done',
        title: 'Logic finished a spawn verification task',
        detail: 'Returned draft code correctly and is waiting for the next assignment.',
        time: '2m',
        durationLabel: '6s',
        tags: ['validation', 'subagent'],
      },
      {
        id: 3,
        actorId: 'vision',
        kind: 'status_change',
        title: 'Vision is sleeping at the document desk',
        detail: 'No OCR workload yet, so the station is resting.',
        time: '5m',
        tags: ['idle'],
      },
    ],
  },
  handoff: {
    label: 'Delegation Handoff',
    delegation: 'Main → Vision',
    workers: [
      {
        id: 'main',
        name: 'Main',
        role: 'Manager / Orchestrator',
        model: 'openai-codex/gpt-5.4',
        status: 'waiting',
        task: 'Waiting for specialist output before final review',
        lastCompleted: 'Assigned UI and data review tasks',
        location: 'Command Desk',
        energy: 'Waiting',
        queue: 1,
        duration: '03m',
        lastActiveLabel: 'just now',
        persona: {
          icon: '👩‍💼',
          tone: 'Calm orchestrator',
          specialty: 'Planning and delegation',
        },
      },
      {
        id: 'vision',
        name: 'Vision',
        role: 'OCR / Image Analyst',
        model: 'google/gemini-2.5-flash',
        status: 'working',
        task: 'Reviewing dashboard mockups and extracting visual notes',
        lastCompleted: 'Prepared document extraction response template',
        location: 'Document Station',
        energy: 'Focused',
        queue: 2,
        duration: '11m',
        lastActiveLabel: 'just now',
        persona: {
          icon: '🧾',
          tone: 'Precise reader',
          specialty: 'Text extraction and image understanding',
        },
      },
      {
        id: 'logic',
        name: 'Logic',
        role: 'Code Drafter',
        model: 'anthropic/claude-sonnet-4-6',
        status: 'done',
        task: 'Completed component draft, awaiting review',
        lastCompleted: 'Suggested worker and timeline types',
        location: 'Dev Desk',
        energy: 'Cooldown',
        queue: 0,
        duration: 'Done',
        lastActiveLabel: '1m ago',
        persona: {
          icon: '👩‍💻',
          tone: 'Systematic builder',
          specialty: 'Readable code and maintainable logic',
        },
      },
    ],
    monitoring: {
      source: 'mock',
      lastUpdatedLabel: 'local preset',
    },
    timeline: [
      {
        id: 1,
        actorId: 'main',
        kind: 'handoff',
        title: 'Main delegated visual review to Vision',
        detail: 'The command desk is waiting for UI observations from the image analyst.',
        time: 'Now',
        targetId: 'vision',
        tags: ['handoff', 'review'],
      },
      {
        id: 2,
        actorId: 'vision',
        kind: 'task_start',
        title: 'Vision is processing visual references',
        detail: 'Gathering structure, readability, and scene-layout notes.',
        time: '1m',
        tags: ['visual', 'review'],
      },
      {
        id: 3,
        actorId: 'logic',
        kind: 'task_done',
        title: 'Logic finished and entered cooldown',
        detail: 'Code draft complete and ready for main review.',
        time: '4m',
        durationLabel: '18s',
        tags: ['code', 'handoff'],
      },
    ],
  },
  blocked: {
    label: 'Blocked Flow',
    delegation: 'Main → Logic',
    workers: [
      {
        id: 'main',
        name: 'Main',
        role: 'Manager / Orchestrator',
        model: 'openai-codex/gpt-5.4',
        status: 'working',
        task: 'Resolving blocker and reshaping next tasks',
        lastCompleted: 'Reviewed current dashboard draft',
        location: 'Command Desk',
        energy: 'Focused',
        queue: 3,
        duration: '09m',
        lastActiveLabel: 'just now',
        persona: {
          icon: '👩‍💼',
          tone: 'Calm orchestrator',
          specialty: 'Planning and delegation',
        },
      },
      {
        id: 'vision',
        name: 'Vision',
        role: 'OCR / Image Analyst',
        model: 'google/gemini-2.5-flash',
        status: 'idle',
        task: 'Monitoring for updated assets or screen captures',
        lastCompleted: 'Finished layout observation summary',
        location: 'Document Station',
        energy: 'Ready',
        queue: 0,
        duration: 'Standby',
        lastActiveLabel: '3m ago',
        persona: {
          icon: '🧾',
          tone: 'Precise reader',
          specialty: 'Text extraction and image understanding',
        },
      },
      {
        id: 'logic',
        name: 'Logic',
        role: 'Code Drafter',
        model: 'anthropic/claude-sonnet-4-6',
        status: 'blocked',
        task: 'Waiting for confirmed runtime contract before integration',
        lastCompleted: 'Prepared draft component interactions',
        location: 'Dev Desk',
        energy: 'Blocked',
        queue: 1,
        duration: 'Blocked',
        lastActiveLabel: 'just now',
        persona: {
          icon: '👩‍💻',
          tone: 'Systematic builder',
          specialty: 'Readable code and maintainable logic',
        },
      },
    ],
    monitoring: {
      source: 'mock',
      lastUpdatedLabel: 'local preset',
    },
    timeline: [
      {
        id: 1,
        actorId: 'logic',
        kind: 'task_failed',
        title: 'Logic hit a contract blocker',
        detail: 'Needs final runtime field mapping before continuing integration work.',
        time: 'Now',
        durationLabel: '24s',
        tags: ['blocked', 'integration'],
      },
      {
        id: 2,
        actorId: 'main',
        kind: 'handoff',
        title: 'Main is re-planning around the blocker',
        detail: 'The manager is preparing a safer fallback implementation path.',
        time: '1m',
        targetId: 'logic',
        tags: ['fallback', 'planning'],
      },
      {
        id: 3,
        actorId: 'vision',
        kind: 'message',
        title: 'Vision is idle and available',
        detail: 'The image analyst can pick up design review work if needed.',
        time: '3m',
        tags: ['available'],
      },
    ],
  },
}
